name: Bug Report
description: File a bug report.
title: "🐛 [Title here]"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of this bug, what is the repo/css issue you can see, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide steps to reproduce this bug.
      placeholder: |
        1. [First Step]
        2. [Second Step]
        3. [and so on...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Provide a clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: Provide a clear and concise description of what happened.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots to help explain this bug, if applicable.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Provide any additional information about this bug.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Final Checks
      options:
        - label: My issue title is descriptive
          required: true
        - label: This is a single bug (multiple bugs should be reported individually)
          required: true

  - type: markdown
    attributes:
      value: Thank you for taking the time to report this bug!